### ISSUE TITLE
Errors displayed while running langtable.py

### ISSUE THREAD

**Issue by ManitK** [apertium/apertium-wiki-tools#2]
While running this script from https://github.com/apertium/apertium-wiki-tools/blob/master/langTable.py  on my command prompt the following error was showed.

**Langtable.py**
C:\Users\admin>cd C:\Python34

C:\Python34>python langtable.py
Traceback (most recent call last):
  File "langtable.py", line 3, in <module>
    from html import html
ImportError: cannot import name 'html'

**Comment by sushain97** [comment]
What file are you running...?

https://github.com/apertium/apertium-wiki-tools/blob/master/langTable.py#L3

does not match your traceback.

**Comment by ManitK** [comment]
Yes this only on

**Comment by ManitK** [comment]
Yeah it does now

**Comment by jonorthwash** [comment]
@ManitK, what?  What about `dixTable.py`?

**Comment by ManitK** [comment]
It worked see the wiki page you will understand

**Comment by jonorthwash** [comment]
Okay, good.  Could you please clarify the problem with `langTable.py`, though?  Your traceback suggests that you're running the wrong file.

**Comment by ManitK** [comment]
the script in this https://github.com/apertium/apertium-wiki-tools/blob/master/langTable.py#L3 and in this https://github.com/apertium/apertium-wiki-tools/blob/master/langTable.py is the same.
I am running that script only.

**Comment by jonorthwash** [comment]
Could you check that the output you pasted is right?  I.e., could you clone a fresh copy of it, and run it without modifying the file?

**Comment by ManitK** [comment]
Ok sure.This is output I got after running the the fresh copy:

Traceback (most recent call last):
  File "langtable.py", line 2, in <module>
    from lxml import etree, html
ImportError: No module named 'lxml'

**Comment by jonorthwash** [comment]
@ManitK, please run `pip install lxml` and try again, letting us know of any new errors.

**Comment by ManitK** [comment]
All the errors showed:

Traceback (most recent call last):
  File "langtable.py", line 2, in <module>
    from lxml import etree, html
ImportError: No module named 'lxml'

C:\Python34>pip install lxml
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last o
ne supporting it. Please upgrade your Python as Python 3.4 won't be maintained a
fter March 2019 (cf PEP 429).
Collecting lxml
  Using cached https://files.pythonhosted.org/packages/e1/f5/5eb3b491958dcfdcfa5
daae3c655ab59276bc216ca015e44743c9c220e9e/lxml-4.4.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: This lxml version requires Python 2.7, 3.5 or later.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\a
dmin\AppData\Local\Temp\pip-install-w47zcs8l\lxml\

**Comment by sushain97** [comment]
Try pip3 install.

**Comment by ManitK** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\admin>cd C:\Python34

C:\Python34>python langtable.py
Traceback (most recent call last):
  File "langtable.py", line 2, in <module>
    from lxml import etree, html
ImportError: No module named 'lxml'

C:\Python34>pip install lxml
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last o
ne supporting it. Please upgrade your Python as Python 3.4 won't be maintained a

C:\Python34>pip3 install
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last o
ne supporting it. Please upgrade your Python as Python 3.4 won't be maintained a
fter March 2019 (cf PEP 429).
ERROR: You must give at least one requirement to install (see "pip help install")

**Comment by ManitK** [comment]
C:\Python34>pip3 install lxml
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last o
ne supporting it. Please upgrade your Python as Python 3.4 won't be maintained a
fter March 2019 (cf PEP 429).
Collecting lxml
  Using cached https://files.pythonhosted.org/packages/e1/f5/5eb3b491958dcfdcfa5
daae3c655ab59276bc216ca015e44743c9c220e9e/lxml-4.4.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: This lxml version requires Python 2.7, 3.5 or later.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\a
dmin\AppData\Local\Temp\pip-install-ns6ijn1a\lxml\

**Comment by sushain97** [comment]
The error is in your output:

> ERROR: This lxml version requires Python 2.7, 3.5 or later.

You'll need to install a newer version of Python or an older version of lxml.

**Comment by ManitK** [comment]
Yeah my PC cannot I have already went over this with Tino Didriksen turns out my OS is faulty and that version of Python cannot be installed.

**Comment by sushain97** [comment]
In that case, I'd find an older version of lxml that doesn't require Py3.5.
